ALTER TABLE "StaffUser"
ADD COLUMN "sessionVersion" INTEGER NOT NULL DEFAULT 1;

ALTER TABLE "Branch"
ADD COLUMN "address" TEXT NOT NULL DEFAULT '',
ADD COLUMN "phone" TEXT NOT NULL DEFAULT '',
ADD COLUMN "taxCode" TEXT NOT NULL DEFAULT '',
ADD COLUMN "receiptFooter" TEXT NOT NULL DEFAULT '';
